FROM wordpress:latest

# Install Xdebug
# if php version is <=7.4 need use xdebug v3.1.5
# RUN pecl install xdebug-3.1.5 \
#     && docker-php-ext-enable xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Install wp-cli
RUN apt-get update && apt-get install -y sudo less mariadb-client
RUN curl -o /bin/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x /bin/wp-cli.phar
RUN cd /bin && mv wp-cli.phar wp
RUN mkdir -p /var/www/.wp-cli/cache && chown www-data:www-data /var/www/.wp-cli/cache
# add wp-cli profiler
RUN wp package install wp-cli/profile-command:@stable --allow-root
# Add developer user
RUN useradd -s /bin/bash developer
