version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    # image: wordpress:latest
    # use dockerfile to add xdebug to initial image
    build:
      dockerfile: ./config/wordpress/dockerfile
    container_name: wordpress
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./:/var/www/html

      # xdebug config files
      - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA}
    networks:
      - wpsite

  phpmyadmin:
    container_name: wordpress_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5555:80
    restart: always
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data: